 
# Базовий образ з Python 3.12 + dev tools
FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Копіюємо requirements.txt у контейнер (опціонально — VS Code і сам це зробить)
COPY requirements.txt /tmp/requirements.txt
COPY run.py /run.py
COPY app /app
COPY alembic /alembic
COPY alembic.ini /alembic.ini


# Встановлюємо Python-залежності
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN pip install alembic
                                 
# Відкриваємо порт
EXPOSE 8000

CMD ["python", "run.py"]