"""add 2 tables

Revision ID: c4fbfc72d873
Revises: 
Create Date: 2025-08-29 17:36:48.381116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fbfc72d873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemsets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('problem_ids', sa.Text(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('last_change_time', sa.DateTime(), nullable=False),
    sa.Column('solving', sa.Text(), nullable=False),
    sa.Column('check_message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'problem_id')
    )
    op.drop_table('users')
    op.drop_table('problems')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('attr', sa.VARCHAR(length=255), nullable=False),
    sa.Column('lang', sa.VARCHAR(length=5), nullable=False),
    sa.Column('cond', sa.VARCHAR(), nullable=False),
    sa.Column('view', sa.VARCHAR(), nullable=False),
    sa.Column('hint', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=10), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('role', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.drop_table('tickets')
    op.drop_table('problemsets')
    # ### end Alembic commands ###
